### PR TITLE
host thank you GIF on Imgur

### PR DESCRIPTION
**Pull request by macklinu**
This image was hosted on HipChat, and I’m not sure if those hosted
files are deleted once our HipChat account is deleted.

### CODE REVIEW

**Comment by macklinu** [comment]
This might be part of a larger issue we extract - _find all images hosted on HipChat in our hubot code and host them somewhere else._ Thoughts?

**Comment by nwest** [comment]
```sh
nwest@ender:~/Projects/DetroitLabs/hubot-badger(masterλ)
» ack uploads.hipchat.com
scripts/chowdy.coffee
18:    msg.send "https://s3.amazonaws.com/uploads.hipchat.com/31582/211417/kAMyD3ixawKfaVX/chowdy.png"

scripts/programming.coffee
18:    msg.send "https://s3.amazonaws.com/uploads.hipchat.com/31582/2534438/304yPKsdFtwQyCw/programming.gif"

scripts/thankyou.coffee
19:        msg.send "https://s3.amazonaws.com/uploads.hipchat.com/31582/209877/5xpLrqT70xRfInI/dwy0i4evvxsvt1rf6ehi.gif"
```

**Comment by nwest** [comment]
Mind fixing those as well?

**Comment by macklinu** [comment]
Chowdy. (yes)

**Pull request merged**
